---
title: "Theory Seminars - Bristol Physics"
---

## 2026

<ul>
  <li style="padding-bottom: 10px">Monday 5th October 2026
    <strong>Tony Short</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote>Recurrence of finite quantum systems
<em>As a finite quantum system evolves, different initial states will evolve very differently. However, it is possible to find a time at which all states return arbitrarily close to their initial configuration. We obtain bounds on the time for this recurrence, by linking it to the mathematical problem of approximating real numbers by rationals.

(based on arXiv:2604.14995)</em></blockquote>
    </details>
  </li>
  <li style="padding-bottom: 10px">Monday 19th October 2026
    <strong>Habib Rostami</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
  <li style="padding-bottom: 10px">Monday 2nd November 2026
    <strong>Speaker TBC</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
  <li style="padding-bottom: 10px">Monday 16th November 2026
    <strong>Natalia Chepiga</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
  <li style="padding-bottom: 10px">Monday 30th November 2026
    <strong>Speaker TBC</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
</ul>

## 2027

<ul>
  <li style="padding-bottom: 10px">Monday 1st February 2027
    <strong>Antonia Mey</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
  <li style="padding-bottom: 10px">Monday 15th February 2027
    <strong>Speaker TBC</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
  <li style="padding-bottom: 10px">Monday 1st March 2027
    <strong>Steve Simon</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
  <li style="padding-bottom: 10px">Monday 15th March 2027
    <strong>Speaker TBC</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
  <li style="padding-bottom: 10px">Monday 19th April 2027
    <strong>Speaker TBC</strong>
    <details><summary><i><u>[Click to expand abstract]</u></i></summary>
      <blockquote><em>Abstract TBA</em></blockquote>
    </details>
  </li>
</ul>
